### ISSUE TITLE
Brainstorm name of package

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/dstoolbox#2]
`snakebox` is taken on pypi.

Let's come up with another name, @grabear! lol

**Comment by grabear** [comment]
lol Ok.  What about these?

`snaker`
`snaked`
`snakes`
`snaketools`
`snakeaid`
`snakeutils`
`snakepack`
`snakebag`
`snakekans`
`snaks`

[`ouroboros`](https://en.wikipedia.org/wiki/Ouroboros)
`uroboros`
Which leads to words like dragon or serpent..

We could also do something like `dstools`, but I think that was the one I was making fun of the other day.

Or `dsutils`, `dsbox`...

**Comment by sdhutchins** [comment]
I love for `snakeutils` yassss  lol

**Comment by grabear** [comment]
Just to reserve it:
https://pypi.org/project/snakeutils/

**Comment by sdhutchins** [comment]
@grabear add me! lol My name is `sdhutchins`.

**Comment by grabear** [comment]
@sdhutchins done.  You're an owner on PyPI now.
